# Generated by Django 5.1.4 on 2025-04-05 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleMapsData',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='location',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='title',
            field=models.CharField(default='Untitled Post', max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
