# Generated by Django 5.1.4 on 2025-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
